- name: "Build Status"
  shield: "github/actions/workflow/status/chirag127/CineSense-Movie-Recommendation-Streamlit-Web-App/ci.yml?branch=main&style=flat-square"
  url: "https://github.com/chirag127/CineSense-Movie-Recommendation-Streamlit-Web-App/actions/workflows/ci.yml"
- name: "License"
  shield: "badge/License-CC%20BY--NC%204.0-lightgrey.svg?style=flat-square"
  url: "https://creativecommons.org/licenses/by-nc/4.0/"
- name: "Python Version"
  shield: "badge/python-3.9%2B-blue.svg?style=flat-square"
  url: "https://www.python.org/downloads/"
- name: "Streamlit"
  shield: "badge/Streamlit-1.29.0-red.svg?style=flat-square"
  url: "https://www.streamlit.io/"
- name: "Docker"
  shield: "badge/Docker-supported-blue.svg?style=flat-square"
  url: "https://www.docker.com/"
